version: "3.9"
services:
  db:
    image: mysql:8.4
    container_name: forumhub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: forumhub
      MYSQL_USER: forum
      MYSQL_PASSWORD: forum
    ports: ["3306:3306"]
    volumes: [ "db_data:/var/lib/mysql" ]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10

  app:
    build: .
    container_name: forumhub-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/forumhub?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: forum
      SPRING_DATASOURCE_PASSWORD: forum
      SECURITY_JWT_SECRET: super_secret_change_me_super_long_key_1234567890
      SECURITY_JWT_EXPIRATION-MS: 86400000
      SPRING_JPA_SHOW-SQL: "true"
    ports: ["8080:8080"]
    depends_on:
      db:
        condition: service_healthy
volumes:
  db_data:
